server {
    listen 8080;

    location / {
        proxy_pass https://gitlab.com/api/v4/projects/56254198/packages/pypi/;
        proxy_set_header Host gitlab.com;
        proxy_ssl_server_name on;

        proxy_set_header Accept-Encoding "";

        sub_filter 'https://gitlab.com/api/v4/projects/56254198/packages/pypi'
                   'https://risepypiproxy74965e39-pypi-proxy.functions.fnc.fr-par.scw.cloud' # 'https://pypi.riseproject.dev'
                   ;
        sub_filter_once off;
        sub_filter_types text/html
                         application/vnd.pypi.simple.v1+html
                         application/vnd.pypi.simple.v1+json;
    }
}
