server {
    listen 8080;
    absolute_redirect off;

    location /simple {
        proxy_pass https://riseproject-dev.github.io/python-wheels/simple;
        proxy_set_header Host riseproject-dev.github.io;
        proxy_ssl_server_name on;

        proxy_set_header Accept-Encoding "";

        sub_filter 'https://riseproject-dev.github.io/python-wheels/simple'
                   'https://pypi.riseproject.dev/simple'
                   ;
        sub_filter_once off;
        sub_filter_types text/html
                         application/vnd.pypi.simple.v1+html
                         application/vnd.pypi.simple.v1+json;
    }

    location /python-wheels/ {
        proxy_pass https://riseproject-dev.github.io;
        proxy_set_header Host riseproject-dev.github.io;
        proxy_ssl_server_name on;

        proxy_set_header Accept-Encoding "";

        sub_filter 'https://riseproject-dev.github.io/python-wheels'
                   'https://pypi.riseproject.dev'
                   ;
        sub_filter_once off;
        sub_filter_types text/html
                         application/vnd.pypi.simple.v1+html
                         application/vnd.pypi.simple.v1+json;
    }

    location / {
        proxy_pass https://riseproject-dev.github.io/python-wheels/;
        proxy_set_header Host riseproject-dev.github.io;
        proxy_ssl_server_name on;

        proxy_set_header Accept-Encoding "";

        sub_filter 'https://riseproject-dev.github.io/python-wheels'
                   'https://pypi.riseproject.dev'
                   ;
        sub_filter_once off;
        sub_filter_types text/html
                         application/vnd.pypi.simple.v1+html
                         application/vnd.pypi.simple.v1+json;
    }
}
