# SPDX-License-Identifier: MIT
name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: rg.fr-par.scw.cloud/rise-python
  IMAGE: pypi-proxy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v4.2.2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0

      - name: Login to Container Registry
        if: github.repository_owner == 'riseproject-dev'
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: nologin
          password: ${{ secrets.SCW_SECRET_KEY }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@9dc751fe249ad99385a2583ee0d084c400eee04e # v5.4.0

      - name: Build and push image
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
        with:
          platforms: linux/amd64
          context: .
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE }}:sha-${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=gha
          cache-to: |
            ${{ github.ref_name == github.event.repository.default_branch && 'type=gha,mode=max' || '' }}
          push: ${{ github.repository_owner == 'riseproject-dev' }}

  deploy:
    if: github.repository_owner == 'riseproject-dev' && github.ref_name == github.event.repository.default_branch
    needs: [build]
    runs-on: ubuntu-latest
    environment: prod
    concurrency:
      group: ${{ github.workflow_ref }}-deploy
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v4.2.2

      - name: Deploy to Scaleway
        run: npm ci && npx serverless@3 deploy
        env:
          REGISTRY: ${{ env.REGISTRY }}
          IMAGE: ${{ env.IMAGE }}
          GITHUB_SHA: ${{ github.sha }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
